// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhlFantasyLeague.api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NhlFantasyLeague.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909194818_AddLeagueToFantasyTeam")]
    partial class AddLeagueToFantasyTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DraftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentOwnerFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOwnerFantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DraftId")
                        .HasColumnType("integer");

                    b.Property<int>("DraftPickId")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("DraftPickId");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("DraftSelections");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.Property<int?>("WinnerFantasyTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayFantasyTeamId");

                    b.HasIndex("HomeFantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("WinnerFantasyTeamId");

                    b.ToTable("FantasyMatchups");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeamSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FantasyTeamSeasons");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.KeeperSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("KeeperSelections");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDefensemanCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveForwardCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveGoalieCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchDefensemanCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchForwardCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchGoalieCount")
                        .HasColumnType("integer");

                    b.Property<int>("KeeperCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumRosterSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProspectCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.NhlTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NhlTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadshotUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NhlTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NhlTeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerGameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyPoints")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomeGame")
                        .HasColumnType("boolean");

                    b.Property<int>("NhlTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentNhlTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NhlTeamId");

                    b.HasIndex("OpponentNhlTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameLogs");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerSeasonStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("HatTricks")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Shutouts")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSeasonStats");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FantasySalary")
                        .HasColumnType("numeric");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("RosterStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SalaryCap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalaryFloor")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.SeasonStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonStandings");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ToFantasyTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromFantasyTeamId");

                    b.HasIndex("ToFantasyTeamId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DraftPickId")
                        .HasColumnType("integer");

                    b.Property<int>("FromFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProspect")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DraftPickId");

                    b.HasIndex("FromFantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.WeeklyFantasyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalieOvertimeLossPoints")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieWinPoints")
                        .HasColumnType("integer");

                    b.Property<int>("HatTrickBonus")
                        .HasColumnType("integer");

                    b.Property<int>("NhlPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShutoutBonus")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFantasyPoints")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("WeeklyFantasyScores");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Draft", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftPick", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "CurrentOwnerFantasyTeam")
                        .WithMany()
                        .HasForeignKey("CurrentOwnerFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentOwnerFantasyTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftSelection", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Draft", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("DraftPick");

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyMatchup", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "AwayFantasyTeam")
                        .WithMany()
                        .HasForeignKey("AwayFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "HomeFantasyTeam")
                        .WithMany()
                        .HasForeignKey("HomeFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "WinnerFantasyTeam")
                        .WithMany()
                        .HasForeignKey("WinnerFantasyTeamId");

                    b.Navigation("AwayFantasyTeam");

                    b.Navigation("HomeFantasyTeam");

                    b.Navigation("Season");

                    b.Navigation("WinnerFantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeam", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.League", "League")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeamSeason", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.KeeperSelection", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Player", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "NhlTeam")
                        .WithMany("Players")
                        .HasForeignKey("NhlTeamId");

                    b.Navigation("NhlTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerGameLog", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "NhlTeam")
                        .WithMany()
                        .HasForeignKey("NhlTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "OpponentNhlTeam")
                        .WithMany()
                        .HasForeignKey("OpponentNhlTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhlTeam");

                    b.Navigation("OpponentNhlTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerSeasonStat", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterEntry", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.SeasonStanding", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Trade", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FromFantasyTeam")
                        .WithMany()
                        .HasForeignKey("FromFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "ToFantasyTeam")
                        .WithMany()
                        .HasForeignKey("ToFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromFantasyTeam");

                    b.Navigation("ToFantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.TradeItem", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId");

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FromFantasyTeam")
                        .WithMany()
                        .HasForeignKey("FromFantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("NhlFantasyLeague.api.Models.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("FromFantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.WeeklyFantasyScore", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.League", b =>
                {
                    b.Navigation("FantasyTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.NhlTeam", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
