// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhlFantasyLeague.api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NhlFantasyLeague.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003175021_AddPlayerPageStyle")]
    partial class AddPlayerPageStyle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerPageStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId")
                        .IsUnique()
                        .HasFilter("\"FantasyTeamId\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.CapFreeze.CapFreezePlayerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapFreezeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FirstNameSimilarity")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<double>("FullNameSimilarity")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<double>("LastNameSimilarity")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<int>("NhlTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CapFreezeName", "PlayerId");

                    b.ToTable("CapFreezePlayerReviews");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DraftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentOwnerFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("DraftId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalOwnerFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOwnerFantasyTeamId");

                    b.HasIndex("OriginalOwnerFantasyTeamId");

                    b.HasIndex("DraftId", "Round", "PickNumber")
                        .IsUnique();

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DraftPickId")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DraftPickId")
                        .IsUnique();

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("DraftSelections");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.ExternalSourceHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceName")
                        .IsUnique();

                    b.ToTable("ExternalSourceHealths");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.Property<int?>("WinnerFantasyTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayFantasyTeamId");

                    b.HasIndex("HomeFantasyTeamId");

                    b.HasIndex("WinnerFantasyTeamId");

                    b.HasIndex("SeasonId", "WeekNumber", "AwayFantasyTeamId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "WeekNumber", "HomeFantasyTeamId")
                        .IsUnique();

                    b.ToTable("FantasyMatchups");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeamSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieLosses")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieOvertimeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("GoaliePoints")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieShutouts")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieWins")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SkaterAssists")
                        .HasColumnType("integer");

                    b.Property<int>("SkaterGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("SkaterGoals")
                        .HasColumnType("integer");

                    b.Property<int>("SkaterHatTricks")
                        .HasColumnType("integer");

                    b.Property<int>("SkaterPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFantasyPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TotalFantasyPointsComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("FantasyTeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("FantasyTeamSeasons");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.KeeperSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "FantasyTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("KeeperSelections");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDefensemanCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveForwardCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveGoalieCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchDefensemanCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchForwardCount")
                        .HasColumnType("integer");

                    b.Property<int>("BenchGoalieCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumRosterSize")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumDropCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProspectCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.NhlTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NhlTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NhlTeamId")
                        .IsUnique();

                    b.ToTable("NhlTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthCity")
                        .HasColumnType("text");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CapFreezeContractLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CapFreezeName")
                        .HasColumnType("text");

                    b.Property<string>("CapFreezeSlug")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CapFreezeStatusLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DraftOverallPick")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftPickInRound")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer");

                    b.Property<string>("DraftTeamAbbreviation")
                        .HasColumnType("text");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadshotUrl")
                        .HasColumnType("text");

                    b.Property<int?>("HeightInInches")
                        .HasColumnType("integer");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InjuryDetail")
                        .HasColumnType("text");

                    b.Property<string>("InjuryFantasyStatus")
                        .HasColumnType("text");

                    b.Property<int>("InjuryKind")
                        .HasColumnType("integer");

                    b.Property<string>("InjuryLongDescription")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InjuryReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("InjuryShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("InjurySide")
                        .HasColumnType("text");

                    b.Property<string>("InjuryStatus")
                        .HasColumnType("text");

                    b.Property<string>("InjuryType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InjuryUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NhlPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("NhlTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PreviousNhlTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("RosterLocation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RosterLocationUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShootsCatches")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WeightInPounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NhlPlayerId")
                        .IsUnique();

                    b.HasIndex("NhlTeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerCareerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<string>("AverageTimeOnIce")
                        .HasColumnType("text");

                    b.Property<decimal?>("FaceoffWinningPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GameWinningGoals")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<decimal>("GoalsAgainstAverage")
                        .HasColumnType("numeric");

                    b.Property<int?>("HatTricks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HatTricksComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeagueAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeGoals")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPlayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPlayPoints")
                        .HasColumnType("integer");

                    b.Property<decimal>("SavePercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("ShootingPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("ShorthandedGoals")
                        .HasColumnType("integer");

                    b.Property<int>("ShorthandedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Shots")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("Shutouts")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Season", "GameTypeId", "Sequence")
                        .IsUnique();

                    b.ToTable("PlayerCareerStats");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndSeason")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StartSeason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "StartSeason")
                        .IsUnique();

                    b.ToTable("PlayerContracts");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerGameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyPoints")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<bool>("GoalieOvertimeLoss")
                        .HasColumnType("boolean");

                    b.Property<bool>("GoalieWin")
                        .HasColumnType("boolean");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<bool>("HatTrick")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHomeGame")
                        .HasColumnType("boolean");

                    b.Property<long>("NhlGameId")
                        .HasColumnType("bigint");

                    b.Property<int>("NhlTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentNhlTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("SavePercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Shots")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("integer");

                    b.Property<bool>("Shutout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NhlTeamId");

                    b.HasIndex("OpponentNhlTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("PlayerId", "NhlGameId")
                        .IsUnique();

                    b.ToTable("PlayerGameLogs");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerInjuryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InjuryDescription")
                        .HasColumnType("text");

                    b.Property<string>("InjuryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeamAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "InjuryStatus", "TeamAbbreviation")
                        .IsUnique()
                        .HasFilter("\"ResolvedAt\" IS NULL");

                    b.ToTable("PlayerInjuryHistories");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerSeasonStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyPoints")
                        .HasColumnType("integer");

                    b.Property<int>("GameWinningGoals")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<decimal>("GoalsAgainstAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("HatTricks")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPlayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPlayPoints")
                        .HasColumnType("integer");

                    b.Property<decimal>("SavePercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ShootingPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Shots")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("Shutouts")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerSeasonStats");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FantasySalary")
                        .HasColumnType("numeric");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlot")
                        .HasColumnType("integer");

                    b.Property<string>("RosterStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "FantasyTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("RosterStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("PlayerId", "SeasonId", "EffectiveAt");

                    b.ToTable("RosterStatusHistories");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NhlSeasonCode")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalaryCap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalaryFloor")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("NhlSeasonCode")
                        .IsUnique();

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.SeasonStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("SeasonId", "FantasyTeamId")
                        .IsUnique();

                    b.ToTable("SeasonStandings");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToFantasyTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromFantasyTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ToFantasyTeamId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DraftPickId")
                        .HasColumnType("integer");

                    b.Property<int>("FromFantasyTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProspect")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DraftPickId");

                    b.HasIndex("FromFantasyTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.WeeklyFantasyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalieOvertimeLossPoints")
                        .HasColumnType("integer");

                    b.Property<int>("GoalieWinPoints")
                        .HasColumnType("integer");

                    b.Property<int>("HatTrickBonus")
                        .HasColumnType("integer");

                    b.Property<int>("NhlPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("ShutoutBonus")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFantasyPoints")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "PlayerId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("WeeklyFantasyScores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.ApplicationUser", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.CapFreeze.CapFreezePlayerReview", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Draft", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftPick", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "CurrentOwnerFantasyTeam")
                        .WithMany()
                        .HasForeignKey("CurrentOwnerFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Draft", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "OriginalOwnerFantasyTeam")
                        .WithMany()
                        .HasForeignKey("OriginalOwnerFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentOwnerFantasyTeam");

                    b.Navigation("Draft");

                    b.Navigation("OriginalOwnerFantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.DraftSelection", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyMatchup", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "AwayFantasyTeam")
                        .WithMany()
                        .HasForeignKey("AwayFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "HomeFantasyTeam")
                        .WithMany()
                        .HasForeignKey("HomeFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "WinnerFantasyTeam")
                        .WithMany()
                        .HasForeignKey("WinnerFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayFantasyTeam");

                    b.Navigation("HomeFantasyTeam");

                    b.Navigation("Season");

                    b.Navigation("WinnerFantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeam", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.League", "League")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.FantasyTeamSeason", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.KeeperSelection", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Player", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "NhlTeam")
                        .WithMany("Players")
                        .HasForeignKey("NhlTeamId")
                        .HasPrincipalKey("NhlTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NhlTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerCareerStat", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerContract", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerGameLog", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "NhlTeam")
                        .WithMany()
                        .HasForeignKey("NhlTeamId")
                        .HasPrincipalKey("NhlTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.NhlTeam", "OpponentNhlTeam")
                        .WithMany()
                        .HasForeignKey("OpponentNhlTeamId")
                        .HasPrincipalKey("NhlTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhlTeam");

                    b.Navigation("OpponentNhlTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerInjuryHistory", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.PlayerSeasonStat", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterEntry", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.RosterStatusHistory", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Season", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.SeasonStanding", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany()
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Trade", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FromFantasyTeam")
                        .WithMany()
                        .HasForeignKey("FromFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "ToFantasyTeam")
                        .WithMany()
                        .HasForeignKey("ToFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromFantasyTeam");

                    b.Navigation("Season");

                    b.Navigation("ToFantasyTeam");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.TradeItem", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId");

                    b.HasOne("NhlFantasyLeague.api.Models.FantasyTeam", "FromFantasyTeam")
                        .WithMany()
                        .HasForeignKey("FromFantasyTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("NhlFantasyLeague.api.Models.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("FromFantasyTeam");

                    b.Navigation("Player");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.WeeklyFantasyScore", b =>
                {
                    b.HasOne("NhlFantasyLeague.api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhlFantasyLeague.api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.League", b =>
                {
                    b.Navigation("FantasyTeams");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.NhlTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("NhlFantasyLeague.api.Models.Player", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
